# Generated by Django 4.1.3 on 2022-11-06 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='studentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('student_phone', models.IntegerField()),
                ('student_address', models.CharField(max_length=100)),
                ('id_created', models.DateTimeField(auto_now_add=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id_created'],
            },
        ),
        migrations.CreateModel(
            name='studentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academics', models.JSONField()),
                ('cocurricular', models.JSONField()),
                ('last_action', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Linkify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('student_id', models.CharField(max_length=100)),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['post_created'],
            },
        ),
    ]
